### PR TITLE
Fix #58 (nil pointer dereference)

### LINKED ISSUE #58: panic on linux mint with v0.3, nil pointer dereference
**Describe the bug**

Panic crash.

Installed v0.3, launched the executable, hit escape key.

**To Reproduce**
- Install v0.3 on linux mint cinnamon
- launch the executable
- Press ESC key

**Expected behaviour**

Dunno, first time I ever ran this program. Not crash though.

**Stack Trace**

```lazydocker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8119a1]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000000f00, 0xc0000da2c0, 0xc0000c0140, 0x0, 0x9d6460, 0xc000320190)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000000f00, 0xc0000da2c0, 0xc0000c0140, 0xc0000c0140, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000000f00, 0xc0000da2c0, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc0000da2c0, 0xc0000c0140, 0xc, 0x1)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0000da2c0, 0xc0000c0140, 0xc0005f5970, 0xc0005a3680, 0xc000000208, 0xc0000002b8)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000da2c0, 0xc0005f5970, 0x2, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000da2c0, 0xc0000da2c0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000000f00, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000000f00, 0xc000320a00, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
	/go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819
```
**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1 Cinnamon, kernel 4.18.0-22-generic
 - Lazydocker Version 0.3
- Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=linux, arch=amd64

### PR DESCRIPTION
**Pull request by mjarkk**
This fixes #58  
We try to fallback on a view that might not exist.  
But that a view requires the project to be a docker-compose project

### CODE REVIEW

File: pkg/gui/view_helpers.go [hunk 1]
```diff
@@ -111,7 +111,11 @@ func (gui *Gui) returnFocus(g *gocui.Gui, v *gocui.View) error {
 		// always fall back to services view if there's no 'previous' view stored
 		previousView, err = g.View("services")
 		if err != nil {
-			gui.Log.Error(err)
+			// Or fall back to the containers view if we are not in a docker-compose project
```
Comment (jesseduffield) [inline pkg/gui/view_helpers.go]: We can instead use gui.initiallyFocusedViewName() here and go 
```
previousView, err = g.View(gui.initiallyFocusedViewName())
```

Comment (mjarkk) [reply pkg/gui/view_helpers.go]: That seems like a better idea, I was searching for something like that but could not find it.

Comment (mjarkk) [reply pkg/gui/view_helpers.go]: Fixed it
